# Generated by Django 2.2.1 on 2019-05-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountID', models.CharField(max_length=200)),
                ('AccountName', models.CharField(max_length=200)),
                ('ScheduleID', models.CharField(max_length=200)),
                ('EndPoint', models.CharField(max_length=200)),
                ('Email', models.CharField(default='', max_length=200)),
                ('FtpUrl', models.CharField(default='', max_length=200)),
                ('FtpUsername', models.CharField(default='', max_length=200)),
                ('FtpPassword', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=200)),
                ('efcid', models.CharField(max_length=200)),
                ('purl', models.CharField(max_length=200)),
                ('grad_year', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('gpa', models.CharField(max_length=200)),
                ('email_inq', models.CharField(max_length=200)),
                ('ethnicity', models.CharField(max_length=200)),
                ('high_school_name', models.CharField(max_length=200)),
                ('high_school_ceeb', models.CharField(max_length=200)),
                ('listsource', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
                ('rank1', models.CharField(max_length=200)),
                ('rank2', models.CharField(max_length=200)),
                ('rank3', models.CharField(max_length=200)),
                ('segment', models.CharField(max_length=200)),
                ('source_filename', models.CharField(max_length=200)),
                ('source_id', models.CharField(max_length=200)),
                ('submit_action', models.CharField(max_length=200)),
                ('sw20k', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('distance', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('qrcode_used', models.CharField(max_length=200)),
                ('race', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InboundDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('month', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('day', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('hour', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('weekday', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('event_info', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('question', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('answer', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('link_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('browser', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('os', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('referring_url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ip_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('campaign', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Campaign')),
                ('contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Contact')),
                ('element_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ServiceType')),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Event')),
                ('inbound', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Inbound')),
                ('outbound', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Outbound')),
                ('page', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.InboundDetail')),
                ('program', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.Program')),
                ('question_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.ResponseType')),
                ('schedule', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.OutboundSchedule')),
            ],
        ),
    ]
